export const siteMetadata = {
  title: "Cremación de Mascotas en Barcelona | Servicio Compasivo",
  description:
    "Ofrecemos servicios de cremación para mascotas en Barcelona con empatía, respeto y atención personalizada. Llámanos hoy para más información.",
  keywords: [
    "cremación de mascotas",
    "cremacion de mascotas Barcelona",
    "cremacion de mascotas perros",
    "cremacion de mascotas gatos",
    "Barcelona",
    "servicio funerario de mascotas",
    "cremacion de perro",
    "cremacion de gato",
    "adiós a tu mascota",
    "tanatorio de mascotas",
    "precio cremacion de perro",
    "precio cremacion de gato",
    "crematorio de mascotas",
    "urna para cenizas de mascotas",
    "despedida de mascotas",
    "cremación individual de mascotas",
    "cremación colectiva de mascotas",
    "recogida de mascotas fallecidas",
    "recogida de mascotas 24h",
    "recogida de perros 24h",
    "duelo por mascota",
    "cremacio de perro 24h",
    "cremacio de gato 24h",
    "cremacio 24h",
  ],
  url: "https://www.luzanimal.com",
  locale: "es_ES",
  siteName: "Luz Animal",
};