export const siteMetadata = {
  title: "Incineracion de Mascotas en Barcelona | Luz Animal",
  description:
    "Incineracion de mascotas en Barcelona con respeto y empatía. Servicio 24h con recogida a domicilio y certificado oficial. Llámanos hoy.",
  keywords: [
    "cremación de mascotas",
    "incineracion mascotas Barcelona",
    "incineracion perros Barcelona",
    "incineracion gatos Barcelona",
    "incineracion perros",
    "incineracion gatos",
    "cremacion de mascotas Barcelona",
    "cremacion de mascotas perros",
    "cremacion de mascotas gatos",
    "Barcelona",
    "servicio funerario de mascotas",
    "cremacion de perro",
    "cremacion de gato",
    "adiós a tu mascota",
    "tanatorio de mascotas",
    "tanatorio de mascotas Barcelona",
    "precio cremacion de perro",
    "precio cremacion de gato",
    "crematorio de mascotas",
    "cremacion urgente mascotas",
    "cremacion mascotas precio Barcelona",
    "como despedir a mi mascota",
    "tanatorio mascotas cerca de mí",
    "incineradora de mascotas",
    "servicio de recogida mascotas fallecidas",
    "cremacion etica animales",
    "cremacion mascotas granollers",
    "adios a mi perro",
    "servicio 24h mascotas fallecidas",
    "urna para cenizas de mascotas",
    "despedida de mascotas",
    "cremación individual de mascotas",
    "cremación colectiva de mascotas",
    "recogida de mascotas fallecidas",
    "recogida de mascotas 24h",
    "recogida de perros 24h",
    "duelo por mascota",
    "cremacio de perro 24h",
    "cremacio de gato 24h",
    "cremacio 24h",
  ],
  url: "https://www.luzanimal.com",
  locale: "es_ES",
  siteName: "Luz Animal",
  canonical: "https://www.luzanimal.com",
};

export const openGraph = {
  type: "website",
  url: siteMetadata.url,
  title: siteMetadata.title,
  description: siteMetadata.description,
  images: [
    {
      url: `${siteMetadata.url}/og.jpg`,
      width: 1200,
      height: 630,
      alt: siteMetadata.title,
    },
  ],
  site_name: siteMetadata.siteName,
};